100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30000/30000 [01:45<00:00, 285.67it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30000/30000 [01:44<00:00, 286.28it/s]
100%|███████████████████████████████████████| 891M/891M [00:39<00:00, 23.7MiB/s]
Epoch 1/100:   0%|                                                                                                                        | 0/1500 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "/home/jayant/sig_lip_train/train_with_head.py", line 213, in <module>
    for images, labels in trainloader:
  File "/home/jayant/miniconda3/envs/pytorch/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/home/jayant/miniconda3/envs/pytorch/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1344, in _next_data
    return self._process_data(data)
  File "/home/jayant/miniconda3/envs/pytorch/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1370, in _process_data
    data.reraise()
  File "/home/jayant/miniconda3/envs/pytorch/lib/python3.10/site-packages/torch/_utils.py", line 706, in reraise
    raise exception
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/jayant/miniconda3/envs/pytorch/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 309, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/home/jayant/miniconda3/envs/pytorch/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/jayant/miniconda3/envs/pytorch/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/jayant/sig_lip_train/train_with_head.py", line 115, in __getitem__
    label = self.label_dict[im_path.split(os.sep)[-2]]
KeyError: 'Train_B'
